#!/bin/sh
#
# git-delete
#
# Created by: Roman Simecek <roman.simecek@good2go.ch>

usage() {
  echo "usage: git delete <branch>"
  echo " "
  echo "By Roman Simecek"
}

source ~/.bash/colors.sh
source "$(git --exec-path)/git-sh-setup"
source /usr/local/etc/bash_completion.d/git-prompt.sh

main() {
  local branch_name=$1

  if [ $# -lt 1 ]; then
    usage
    exit 1
  fi

  if [ "$branch_name" == "" ]; then
    echo 'Branch is missing'
    usage
    exit 1
  fi

  local exists_local=$(git show-ref refs/heads/"$branch_name")

  if $(git diff-files --quiet --ignore-submodules --); then

    echo "Do you want to delete '$branch_name' [yN]: \c"
    read -e prepare_release

    if [ "$prepare_release" == "y" ]; then
      git branch -d "$branch_name"

      if git ls-remote | grep -sw "$branch_name" 2>&1>/dev/null; then
        git push origin :"$branch_name"
      fi
    fi
  else
    echo 'Aborting cause of uncommited files'
    exit 1
  fi
}

_git_delete() {
  main
}

main "$@"
