#!/usr/bin/env rvm default do ruby
#
# git-redmine-merge
#
# Created by: Roman Simecek <roman.simecek@swisslife-select.ch>
#
require_relative "git_commander"

ARGV.unshift("redminemerge")
GitCommander.new.run if $0 == __FILE__
